apiVersion: v1
kind: Service
metadata:
  name: servicenp
spec:
  type: NodePort
  ports:
    - targetPort: 5630
      port: 80
      nodePort: 30008
  selector:
    app: product
    type: productapi
    