apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
  - name: webappimg
    image: kodekloud/event-simulator
    volumeMounts:
    - name: webappvolume
      mountPath: /log
  volumes:
  - name: webappvolume
    persistentVolumeClaim:
      claimName: claim-log-1
