apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQTBRcWRXWElQVDJiWE5zKzc4anVWWE4zQk5CTWJTSyt2enlOb3lMMUlOcFZZCno3SCtWRmpLSEJtWGprNS9Ud3FuZ3RwNSt1NUZraWdnandHbmM4c0szdUNiNmVTN1V0aW1MSDlBbkJmTVNlY0cKNExPbmgyUTcxdndvNUZ0d1pWQjdRSythNzI2VmpMY1dkczhuaVc1TEUvVTNZRm9vTVRWU1ZqN1J0M1J3cGxwRAozMGEyRk5rcUE4UzE3Sko2K3FQZDBrQ2JDbFlVbFpKQjJjQWFlUDBOZkNKRzBzOHJ6TU10b3RlT2hYYmY0WjJ5CkNJU0ZjYTlJVzU1N051OTJDQldqaVV1RmFmZkQ5RVowU0xCck9pejRRT050ajBPa1pzQnVhK3ZhUEdEMVRhb3YKT3ZueGtwODkrcTZwekh5VzMyb0tGMU42UlZSbi9BMWU2QitmU2NrdTZ3SURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBRE0zRDlWeUxPMUNNMW9xMGd4M1JPcDF4TTF5a1c5M3lKUksrK2lBT0RzNDk3WFA4c3k2CkpNS2toWWRPa3UxcU9GeW8rNDJoaG96SUtYTTROV1pBdUVDSmtoQ0p1Sis1aG1URm5hdllld0ViaWMyTExMSFEKajdqTkF6VlIyNHVkQVFnam42T1p2amNTUTZ2MVVlSWdEV2IrM0xreU45bVN6bFJkeWNodWJCT0RXdnVEclhYdgpSK3dRRVJoZklEaGJxQW5wMkZ0RU1IcVBQTkNOVWJmbVVMSDVVNTJBRW43YVlSSFNIdWp1V2lNenRnZUM4cE11CmFUa1M0bWxBUmhzRzJ0ZjVmODNCUDJKU3BOTmhnaGkyb0dtUW1tL3ZscDh4MDZ6Z1pseWx2NTAzTHI0Y3pyMzMKTldWUitFVlNQZ2N5RnQveTZvWWR5TW5OQk84YjVHL3NPaTg9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:
  - digital signature
  - key encipherment
  - server auth
